// type of operator tells type of data type
var test1 = typeof("what")
var test2 = typeof('c')
var test3 = typeof("2")
var test4 = typeof(2)
var test5 = typeof(true)
var test6 = typeof(1<2)
var test7 = typeof([1,2,3])
var test8 = typeof({name:"john",age:30})
var test9 = typeof(function abs(){console.log('abc')})
console.log(test1)
console.log(test2)
console.log(test3)
console.log(test4)
console.log(test5)
console.log(test6)
console.log(test7)
console.log(test8)
console.log(test9)